module(
    name = "ttx",
    version = "0.3.0-dev.1",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "tetro_toolchain", version = "0.3.0-dev.2")
archive_override(
    module_name = "tetro_toolchain",
    sha256 = "0bf7f46397e8f5062145c7b00b5ca77d9dd60ace19008828eb5b8a5c50e00f49",
    urls = ["https://github.com/tetrodotoxin-dev/Toolchain/releases/download/v0.3.0-dev.2/tetro_toolchain-0.3.0-dev.2-source.tar.gz"],
)

register_toolchains("@tetro_toolchain//:cc_toolchain_for_linux_x86_64", "@tetro_toolchain//:cc_toolchain_for_wasm32", "@tetro_toolchain//:cc_toolchain_for_windows_x64")

sdks = use_extension("@tetro_toolchain//source/bazel:sdk.bzl", "dependencies")
sdks.release(
    name = "perimortem",
    archives = {
        "headers": "2c545626c116573cc29d166f9fbf9735c0514b9771dd4eed5b89641532575e38",
        "linux-x86_64-v3-static": "5e3e235ce88303a41fca562d2c75721eedf4a1ebb62cc937ab210a74d9580f28",
        "windows-x86_64-msvc-static": "38c33eeee331259e2bd68ed7ecbf8a46b424e6779770e5bc0cf43ac022344017",
        "wasm32-emscripten-static": "d9a461834713ce609bf99026d28dc87ba344edd1940d20fd5b7276931e6e149d",
    },
    linkage = "static",
    project = "Perimortem",
    version = "0.3.0-dev.1",
    deps = [],
)
use_repo(sdks, "perimortem")
